#!/usr/bin/env Rscript
options(stringsAsFactors=FALSE)

.parse <- function(args){o<-list(deployment_dir=NULL,repo_root=NULL,release_dir=NULL,expected_release_id=NULL,result_path=NULL);for(a in args){if(!grepl('^--[^=]+=',a))stop('args use --key=value',call.=FALSE);k<-gsub('-','_',sub('^--([^=]+)=.*$','\\1',a));v<-sub('^--[^=]+=','',a);if(!k%in%names(o))stop('unknown preflight arg',call.=FALSE);o[[k]]<-v};if(any(vapply(o,is.null,logical(1))))stop('missing preflight arg',call.=FALSE);o}
.sha <- function(path){x<-system2('sha256sum',path,stdout=TRUE,stderr=TRUE);if(!length(x))stop('sha256sum failed',call.=FALSE);strsplit(x[[1]],' +')[[1]][[1]]}
.dep_id <- function(d){
  m<-read.delim(file.path(d,'deployment_manifest.tsv'),sep='\t',stringsAsFactors=FALSE,check.names=FALSE);if(!identical(names(m),c('role','path','sha256','size_bytes')))stop('manifest columns',call.=FALSE);m$size_bytes<-as.character(m$size_bytes);m<-m[order(m$role,m$path,method='radix'),,drop=FALSE]
  mt<-paste0(paste(apply(m,1,function(r)paste(r,collapse='\t')),collapse='\n'),'\n');c<-read.delim(file.path(d,'effective_config.tsv'),sep='\t',stringsAsFactors=FALSE,check.names=FALSE);if(!identical(names(c),c('key','value'))||anyDuplicated(c$key))stop('config columns',call.=FALSE);kv<-setNames(as.character(c$value),as.character(c$key));kv<-kv[order(names(kv),method='radix')];ct<-paste0(paste0(names(kv),'\t',kv,collapse='\n'),'\n');tf<-tempfile();on.exit(unlink(tf),add=TRUE);con<-file(tf,'wb');writeBin(charToRaw(enc2utf8(paste0(mt,'--effective-config--\n',ct))),con);close(con);id<-.sha(tf);rec<-trimws(readLines(file.path(d,'deployment_id.txt'),n=1L,warn=FALSE));if(!identical(id,rec)||!identical(basename(normalizePath(d,winslash='/',mustWork=TRUE)),id))stop('deployment identity',call.=FALSE);list(id=id,m=m)
}
.bootstrap <- function(d,repo){z<-.dep_id(d);needed<-c('scripts/v3_weekly_api_deployment_helpers_v4.R','scripts/v3_weekly_api_helpers_v4.R','scripts/v3_shadow_release_helpers_v1.R','scripts/v3_shadow_ops_helpers_v1.R','scripts/v3_probability_helpers_v1.R','2026/run_page_probability_snapshot_v1.R','scripts/v3_a_shadow_helpers_v1.R','2026/run_page_a_shadow_snapshot_v1.R');for(rel in needed){r<-z$m[z$m$path==rel,,drop=FALSE];if(nrow(r)!=1L||!identical(.sha(file.path(repo,rel)),r$sha256[[1]]))stop('bootstrap drift',call.=FALSE)};z$id}
.atomic_json <- function(x,path){if(!requireNamespace('jsonlite',quietly=TRUE))stop('jsonlite missing',call.=FALSE);dir.create(dirname(path),recursive=TRUE,mode='0700',showWarnings=FALSE);tmp<-tempfile(tmpdir=dirname(path));writeLines(jsonlite::toJSON(x,auto_unbox=TRUE,null='null',pretty=FALSE),tmp,useBytes=TRUE);Sys.chmod(tmp,'0600');if(!file.rename(tmp,path))stop('preflight result rename failed',call.=FALSE)}
.main <- function(){o<-.parse(commandArgs(trailingOnly=TRUE));repo<-normalizePath(o$repo_root,winslash='/',mustWork=TRUE);setwd(repo);dep<-normalizePath(o$deployment_dir,winslash='/',mustWork=TRUE);ok<-FALSE;code<-'preflight_failed';tryCatch({id<-.bootstrap(dep,repo);source('scripts/v3_weekly_api_deployment_helpers_v4.R');source('scripts/v3_weekly_api_helpers_v4.R');.api_deployment_validate(dep,repo,expected_id=id,validate_environment=TRUE);source('scripts/v3_shadow_release_helpers_v1.R');.v3_release_validate(o$release_dir,expected_id=o$expected_release_id);ok<-TRUE;code<-'ok'},error=function(e){ok<<-FALSE;code<<-'preflight_failed'});.atomic_json(list(ok=ok,code=code,checked_utc=format(Sys.time(),'%Y-%m-%dT%H:%M:%SZ',tz='UTC')),o$result_path);if(!ok)quit(status=1L)}
if(sys.nframe()==0L).main()
