---
title: ""
format:
  html:
    page-layout: full
    grid:
      body-width: 1200px
editor: visual
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

library(tidyverse)
library(mgcv)
library(gamm4)
library(gratia)
library(ggplot2)
library(plotly)
library(kableExtra)
library(purrr)
library(glue)
library(quartabs)
library(htmltools)
library(data.table)
library(ISOweek)
library(MMWRweek)
library(openxlsx2)
library(flualign)
lastWeek <- 44
#weekF: aligned at week 27
#weekS: aligned at week 35
#data = "https://ws1.publichealthontario.ca/appdata/powerbi/ORVT/ORVT_Lab_Testing_Data_2024-25_2025-26.csv"



load_refCurve()  # load reference curve
currentSeason <- getCurrentD() ## to change to surveillance week number as last observed week
L = median(checkSeasonLength(theD)$season_length_weeks)

####past season data used in estimation ref curve
ggplotly(ggplot(theD, aes(x = weekS, y = p, group = season, color = season)) + geom_point() + geom_line() +
  xlab("Season Week: aligned to start at 35"))

####smoothed past season curves
ggplotly(ggplot(predDS, aes(x = weekF, y = p, group = season, color = season)) + geom_point() +
            xlab("Week") + 
            geom_line(aes(y = fit), linewidth = 1) +
            geom_ribbon(aes(x = weekF, ymin = low, ymax = high), alpha = 0.2) +
            ylab("Proportion of positive tests") )

##############plot estimated ref curve with aligned past seasons
ggplotly(ggplot(theD, aes(x = newWeek, y = p, group = season, color = season)) + 
            geom_point(alpha = 0.5)  + geom_line(alpha = 0.5)+
            xlab("Week aligned") + 
            geom_line(data = predD, aes(x = newWeek, y = fit), color = "black", linewidth = 1.5) +
            geom_ribbon(data = predD, aes(x = newWeek, ymin = low, ymax = high), alpha = 0.2) +
            geom_vline(xintercept = theD$anchorWeek[1], linetype = "dashed") +
            ylab("Proportion of positive tests") + ggtitle("GAM fit with common trend"))
```


## Alignment hyperparameters and forecast
```{r, eval=FALSE}
##check dilation
scale_diag <- check_scale_identifiability(currentD  = currentSeason,g_ref_fun = g_ref_fun, hyper= hyper)
print(scale_diag)


res <- align_forecast_pipeline_dilate(currentSeason, g_ref_fun= g_ref_fun, g_ref_mu_se = g_ref_mu_se,hyper = hyper,allow_scale =scale_diag$allow_scale_rec,  level = 0.95)

cat(sprintf(" taû=%.2f, deltâ=%.3f%s | Peak week ~ %.1f (95%% CI [%.1f, %.1f]) | Peak p=%.3f\n",
            res$tau, res$delta,
            if (is.na(res$fallback_reason)) "" else " [τ-only fallback]",
            res$peak$t_peak, res$peak$t_peak_ci[1], res$peak$t_peak_ci[2],
            res$peak$p_peak))

plotRes(res) 
```