t <- readRDS("data/stage1_tuning.rds")
cat("=== Names ===\n")
print(names(t))
cat("\n=== best_params ===\n")
print(t$best_params)
cat("\n=== compare (head) ===\n")
if (!is.null(t$compare)) print(head(t$compare, 20))
cat("\n=== best_params_by_fold ===\n")
if (!is.null(t$best_params_by_fold)) print(t$best_params_by_fold)
cat("\n=== summary ===\n")
if (!is.null(t$summary)) print(head(t$summary, 20))
