# Deprecated compatibility entry point.
#
# M1-v2 calibration and passage-policy training require activation coordinates
# generated by an M0 LOSO result from the exact outer training-season universe.
# The earlier version of this script accepted a raw activation data frame and is
# intentionally no longer valid because that bypasses the M0 provenance guard.
#
# Use the authoritative strictly nested replay instead.
message("Delegating to governed nested-M0 M1-v2 replay")
source("scripts/replay_m1_v2_governed_nested_m0.R")
