d <- readRDS('artifacts/expert-ignition-annotation-v2-pass1/campaign_data.rds')
shape <- read.csv('artifacts/m1-peak-aligned-shape-v1/peak_aligned_smoothed_grid.csv', stringsAsFactors=FALSE)
peaks <- read.csv('artifacts/expert-ignition-annotation-v2-pass1/retrospective_peak_truth_v1.csv', stringsAsFactors=FALSE)
m0cmp <- read.csv('artifacts/m0-v2-decimal-loso-baseline-r2/compare.csv', stringsAsFactors=FALSE)
Amap <- setNames(m0cmp$iWeek_hatF,m0cmp$season); Tmap<-setNames(peaks$peak_week_decimal,peaks$season)
seasons<-intersect(names(Amap),names(Tmap))
peak_height<-tapply(shape$p_smooth,shape$season,max,na.rm=TRUE);shape$p_norm<-shape$p_smooth/peak_height[shape$season]
tau_grid<-seq(-14,3,by=.1)
M<-matrix(NA_real_,nrow=length(seasons),ncol=length(tau_grid),dimnames=list(seasons,NULL))
for(i in seq_along(seasons)){z<-shape[shape$season==seasons[i],];M[i,]<-approx(z$tau,z$p_norm,xout=tau_grid,rule=1)$y}

pc_bounds<-function(mu,l,sd_c,k=2.5,eps=.001){i0<-which.min(abs(tau_grid));m0<-mu[i0];l0<-l[i0];lo<--k*sd_c;hi<-k*sd_c;for(j in seq_along(mu)){if(j==i0)next;a<-l[j]-l0;b<-m0-mu[j];if(a>1e-12)hi<-min(hi,b/a);if(a< -1e-12)lo<-max(lo,b/a);a2<-l[j];b2<-eps-mu[j];if(a2>1e-12)lo<-max(lo,b2/a2);if(a2< -1e-12)hi<-min(hi,b2/a2)};c(lo=lo,hi=hi)}
library_for<-function(h){keep<-seasons!=h;X<-M[keep,,drop=FALSE];pc<-prcomp(X,center=TRUE,scale.=FALSE);mu<-pc$center;l<-pc$rotation[,1];sc<-pc$x[,1];recon<-sweep(outer(sc,l),2,mu,'+');rs<-pmax(apply(X-recon,2,sd),.025);bh<-peak_height[seasons[keep]];sdc<-max(sd(sc),.2);bd<-pc_bounds(mu,l,sdc);list(tau=tau_grid,mean=mu,pc1=l,resid_sd=rs,sd_c=sdc,c_lo=bd['lo'],c_hi=bd['hi'],mu_logb=mean(log(bh)),sd_logb=max(sd(log(bh)),.2))}
logev<-function(obs,T,lib,bgrid,cgrid){tau<-obs$weekF-T;if(any(tau<min(lib$tau)|tau>max(lib$tau)))return(-Inf);f0<-approx(lib$tau,lib$mean,xout=tau)$y;v1<-approx(lib$tau,lib$pc1,xout=tau)$y;rs<-approx(lib$tau,lib$resid_sd,xout=tau)$y;bc<-expand.grid(b=bgrid,c=cgrid);F<-matrix(f0,nrow=nrow(bc),ncol=length(f0),byrow=TRUE)+outer(bc$c,v1);F<-pmax(F,.001);MU<-F*bc$b;VV<-(outer(bc$b,rs))^2+MU*(1-MU)/matrix(pmax(obs$N,1),nrow=nrow(bc),ncol=nrow(obs),byrow=TRUE);VV<-pmax(VV,1e-6);YY<-matrix(obs$p,nrow=nrow(bc),ncol=nrow(obs),byrow=TRUE);S<-rowSums((YY-MU)^2/VV+log(VV))+((log(bc$b)-lib$mu_logb)/lib$sd_logb)^2+2*log(bc$b)+(bc$c/lib$sd_c)^2;m<-min(S);-.5*m+log(sum(exp(-.5*(S-m))))}

bgrid<-seq(.08,.44,.02);rows<-list()
for(s in seasons){dd<-d[d$season==s,];dd<-dd[order(dd$weekF),];A<-Amap[[s]];Ttrue<-Tmap[[s]];lib<-library_for(s);cgrid<-seq(lib$c_lo,lib$c_hi,length.out=15);for(o in seq(ceiling(A),min(max(dd$weekF),ceiling(Ttrue)+2),1)){obs<-dd[dd$weekF>=ceiling(A)&dd$weekF<=o,];lower<-o-3;upper<-min(o+12,min(obs$weekF)+14,40);cands<-seq(lower,upper,.1);le<-vapply(cands,function(tc)logev(obs,tc,lib,bgrid,cgrid),numeric(1));ok<-is.finite(le);if(!any(ok))next;le[!ok]<--Inf;w<-exp(le-max(le));w<-w/sum(w);asof<-o+1;rows[[length(rows)+1]]<-data.frame(season=s,A=A,origin=o,asof_boundary=asof,true_peak=Ttrue,truth_confirm=ceiling(Ttrue)-1,p_passed=sum(w[cands<=asof]),p_within1=sum(w[cands>asof&cands<=asof+1]),p_within2=sum(w[cands>asof&cands<=asof+2]))}}
out<-do.call(rbind,rows);dir.create('artifacts/m1-c-passage-lowrank-v4-constrained',recursive=TRUE,showWarnings=FALSE);write.csv(out,'artifacts/m1-c-passage-lowrank-v4-constrained/per_origin_posterior.csv',row.names=FALSE)
# Add decline diagnostics.
xx<-list();for(s in seasons){z<-d[d$season==s,];z<-z[order(z$weekF),];z$raw_diff1<-c(NA,diff(z$p));z$raw_two_down<-c(FALSE,FALSE,head(diff(z$p),-1)<0&tail(diff(z$p),-1)<0);z$raw_runmax<-cummax(z$p);z$raw_drop<-1-z$p/z$raw_runmax;p<-out[out$season==s,];xx[[s]]<-merge(p,z[,c('weekF','p','raw_diff1','raw_two_down','raw_drop')],by.x='origin',by.y='weekF',all.x=TRUE)};x<-do.call(rbind,xx)
pol<-expand.grid(high_thr=c(.8,.9,.95),low_thr=c(.1,.2,.3,.4),drop_frac=c(.03,.05,.08,.10),min_post_A=c(3,4),KEEP.OUT.ATTRS=FALSE);pol$policy_id<-seq_len(nrow(pol))
applypol<-function(s,r){z<-x[x$season==s,];z<-z[order(z$origin),];cf<-NA_real_;branch<-NA_character_;for(i in seq_len(nrow(z))){if(z$origin[i]<ceiling(Amap[[s]])+r$min_post_A)next;fast<-z$p_passed[i]>=r$high_thr&&is.finite(z$raw_diff1[i])&&z$raw_diff1[i]<0;sus<-z$p_passed[i]>=r$low_thr&&isTRUE(z$raw_two_down[i])&&is.finite(z$raw_drop[i])&&z$raw_drop[i]>=r$drop_frac;if(fast||sus){cf<-z$origin[i];branch<-if(fast)'high_posterior_decline' else 'sustained_decline';break}};tc<-ceiling(Tmap[[s]])-1;data.frame(season=s,policy_id=r$policy_id,confirm_origin=cf,branch=branch,truth_confirm=tc,false_early=is.finite(cf)&&cf<tc,early_weeks=if(is.finite(cf))max(tc-cf,0) else NA_real_,delay=if(is.finite(cf))max(cf-tc,0) else NA_real_,miss_by_peak2=!is.finite(cf)||cf>tc+2)}
all<-do.call(rbind,lapply(seq_len(nrow(pol)),function(i)do.call(rbind,lapply(seasons,function(s)applypol(s,pol[i,])))));all<-merge(all,pol,by='policy_id');write.csv(all,'artifacts/m1-c-passage-lowrank-v4-constrained/hybrid_policy_all_seasons.csv',row.names=FALSE)
sel<-list();for(h in seasons){tr<-all[all$season!=h,];ag<-do.call(rbind,lapply(split(tr,tr$policy_id),function(z)data.frame(policy_id=z$policy_id[1],nf=sum(z$false_early),early=sum(z$early_weeks,na.rm=TRUE),miss=sum(z$miss_by_peak2),delay=mean(z$delay[is.finite(z$delay)]),high=z$high_thr[1],drop=z$drop_frac[1],minA=z$min_post_A[1])));ag<-ag[order(ag$nf,ag$early,ag$miss,ag$delay,-ag$high,-ag$drop,-ag$minA),];sel[[h]]<-all[all$season==h&all$policy_id==ag$policy_id[1],]};loso<-do.call(rbind,sel);write.csv(loso,'artifacts/m1-c-passage-lowrank-v4-constrained/hybrid_loso_selected.csv',row.names=FALSE);cat('CONSTRAINED HYBRID LOSO\n');print(loso[,c('season','high_thr','low_thr','drop_frac','min_post_A','truth_confirm','confirm_origin','branch','false_early','delay','miss_by_peak2')],row.names=FALSE,digits=3);cat('false=',sum(loso$false_early),' by+2=',sum(!loso$miss_by_peak2),'/',nrow(loso),' mean delay=',mean(loso$delay[is.finite(loso$delay)]),' median=',median(loso$delay[is.finite(loso$delay)]),'\n',sep='')
